apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod
spec:
  serviceName: mongodb-service
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        replicaset: MainRepSet
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - MainRepSet
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-container
          #image: pkdone/mongo-ent:3.4
          image: mongo
          command:
            - "bash"
            - "-c"
            # - >
            #   ls -l /etc/secrets-volume
            - >
              mongod --wiredTigerCacheSizeGB 0.25 --bind_ip 0.0.0.0
              --replSet MainRepSet --auth --clusterAuthMode keyFile
              --keyFile /etc/secrets-volume/mongosecret
              --setParameter authenticationMechanisms=SCRAM-SHA-1
          resources:
            requests:
              cpu: 1
              memory: 300Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              # readOnly: true
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
            - name: mongodb-persistent-storage-claim
              mountPath: /data/db
          securityContext:
            runAsUser: 0
      volumes:
        - name: secrets-volume
          secret:
            secretName: mongosecret
            # https://coderstoolbox.net/number/
            # Convert to octal to decimal because kube only accepts
            # decimal as input
            defaultMode: 256
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
# ---
# Google cloud
# kind: StorageClass
# apiVersion: storage.k8s.io/v1beta1
# metadata:
#   name: fast
# provisioner: kubernetes.io/gce-pd
# parameters:
#   type: pd-ssd
---
# Local storage
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
provisioner: k8s.io/minikube-hostpath